/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AnniWork;

/**
 *
 * @author alokk
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form UserInfo
     */
    public Profile() {
        initComponents();
        EditMailtxt.setVisible(false);
        EditNametxt.setVisible(false);
        EditNumtxt.setVisible(false);
        ConfirmPassword.setVisible(false);
        NewPassword.setVisible(false);
        ChangePass_Button.setVisible(false);
        EditBackButton.setVisible(false);
        EditProfileButton.setVisible(false);
        BackButton.setVisible(false);
        Securitytxt.setVisible(false);
        EditAgetxt.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserInfoPanel = new javax.swing.JPanel();
        UserInfoLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        NumLabel = new javax.swing.JLabel();
        MailLabel = new javax.swing.JLabel();
        Nametxt = new javax.swing.JTextField();
        Numtxt = new javax.swing.JTextField();
        Mailtxt = new javax.swing.JTextField();
        AgeLabel = new javax.swing.JLabel();
        Agetxt = new javax.swing.JTextField();
        ChangePassPanel = new javax.swing.JPanel();
        ChangePasswordLabel = new javax.swing.JLabel();
        ConfirmLabel = new javax.swing.JLabel();
        ChangePass_Button = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        NewPassword = new javax.swing.JPasswordField();
        ConfirmPassword = new javax.swing.JPasswordField();
        SecurityLabel = new javax.swing.JLabel();
        Securitytxt = new javax.swing.JTextField();
        SidePanel = new javax.swing.JPanel();
        HeyUserLabel = new javax.swing.JLabel();
        UserIcon = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        ChangePassButton = new javax.swing.JButton();
        EditPanel = new javax.swing.JPanel();
        EditNameLabel = new javax.swing.JLabel();
        EditMailLabel = new javax.swing.JLabel();
        EditNumLabel = new javax.swing.JLabel();
        EditProfileButton = new javax.swing.JButton();
        EditBackButton = new javax.swing.JButton();
        EditNametxt = new javax.swing.JTextField();
        EditMailtxt = new javax.swing.JTextField();
        EditNumtxt = new javax.swing.JTextField();
        EditNameLabel2 = new javax.swing.JLabel();
        EditAgetxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserInfoPanel.setBackground(new java.awt.Color(204, 204, 204));

        UserInfoLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 42)); // NOI18N
        UserInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserInfoLabel.setText("User Information");
        UserInfoLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 102, 0)));

        NameLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        NameLabel.setText("Name");

        NumLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        NumLabel.setText("Contact Number");

        MailLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        MailLabel.setText("Email");

        Nametxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Numtxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Numtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumtxtActionPerformed(evt);
            }
        });

        Mailtxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Mailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailtxtActionPerformed(evt);
            }
        });

        AgeLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        AgeLabel.setText("Age");

        Agetxt.setPreferredSize(new java.awt.Dimension(64, 28));
        Agetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgetxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserInfoPanelLayout = new javax.swing.GroupLayout(UserInfoPanel);
        UserInfoPanel.setLayout(UserInfoPanelLayout);
        UserInfoPanelLayout.setHorizontalGroup(
            UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserInfoPanelLayout.createSequentialGroup()
                .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserInfoPanelLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(UserInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserInfoPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(UserInfoPanelLayout.createSequentialGroup()
                                .addComponent(AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(UserInfoPanelLayout.createSequentialGroup()
                                .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(304, 304, 304)
                                .addComponent(Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserInfoPanelLayout.createSequentialGroup()
                                .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumLabel)
                                    .addComponent(MailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Mailtxt)
                                    .addComponent(Numtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        UserInfoPanelLayout.setVerticalGroup(
            UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserInfoPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(UserInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumLabel)
                    .addComponent(Numtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MailLabel)
                    .addComponent(Mailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AgeLabel)
                    .addComponent(Agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        getContentPane().add(UserInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 0, 790, 650));

        ChangePassPanel.setBackground(new java.awt.Color(204, 204, 204));
        ChangePassPanel.setPreferredSize(new java.awt.Dimension(790, 444));

        ChangePasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ChangePasswordLabel.setText("Enter New Password");

        ConfirmLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ConfirmLabel.setText("Confirm Password");

        ChangePass_Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ChangePass_Button.setText("Change Password");
        ChangePass_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePass_ButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        NewPassword.setText("jPasswordField1");

        ConfirmPassword.setText("jPasswordField2");
        ConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordActionPerformed(evt);
            }
        });

        SecurityLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SecurityLabel.setText("What is you favourite movie?");

        Securitytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecuritytxtActionPerformed(evt);
            }
        });
        Securitytxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SecuritytxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout ChangePassPanelLayout = new javax.swing.GroupLayout(ChangePassPanel);
        ChangePassPanel.setLayout(ChangePassPanelLayout);
        ChangePassPanelLayout.setHorizontalGroup(
            ChangePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePassPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(ChangePass_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(ChangePassPanelLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(ChangePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChangePassPanelLayout.createSequentialGroup()
                        .addComponent(ConfirmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChangePassPanelLayout.createSequentialGroup()
                        .addGroup(ChangePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChangePasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SecurityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ChangePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Securitytxt)
                            .addComponent(NewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))))
                .addGap(117, 117, 117))
        );
        ChangePassPanelLayout.setVerticalGroup(
            ChangePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePassPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ChangePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecurityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Securitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(ChangePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangePasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addGroup(ChangePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addGroup(ChangePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangePass_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );

        getContentPane().add(ChangePassPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 790, 650));

        SidePanel.setBackground(new java.awt.Color(102, 102, 102));

        HeyUserLabel.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        HeyUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeyUserLabel.setText("HEY USER !!!");
        HeyUserLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 102, 0)));

        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voice_13125512 (2).png"))); // NOI18N

        ExitButton.setBackground(new java.awt.Color(102, 102, 102));
        ExitButton.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        ExitButton.setText("EXIT");
        ExitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 3));
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        EditButton.setBackground(new java.awt.Color(102, 102, 102));
        EditButton.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        EditButton.setText("EDIT PROFILE");
        EditButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 3));
        EditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditButtonMouseClicked(evt);
            }
        });
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        ChangePassButton.setBackground(new java.awt.Color(102, 102, 102));
        ChangePassButton.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        ChangePassButton.setText("CHANGE PASSWORD");
        ChangePassButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 3));
        ChangePassButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePassButtonMouseClicked(evt);
            }
        });
        ChangePassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePassButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(HeyUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(UserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangePassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(UserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HeyUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(ChangePassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        getContentPane().add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 650));

        EditPanel.setBackground(new java.awt.Color(204, 204, 204));

        EditNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EditNameLabel.setText("Name");

        EditMailLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EditMailLabel.setText("Emaill");

        EditNumLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EditNumLabel.setText("Mobile Number");

        EditProfileButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EditProfileButton.setText("Save Changes");
        EditProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileButtonActionPerformed(evt);
            }
        });

        EditBackButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EditBackButton.setText("Back");
        EditBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBackButtonMouseClicked(evt);
            }
        });

        EditNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditNametxtActionPerformed(evt);
            }
        });

        EditNameLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EditNameLabel2.setText("Age");

        javax.swing.GroupLayout EditPanelLayout = new javax.swing.GroupLayout(EditPanel);
        EditPanel.setLayout(EditPanelLayout);
        EditPanelLayout.setHorizontalGroup(
            EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditPanelLayout.createSequentialGroup()
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EditPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(EditProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EditPanelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditPanelLayout.createSequentialGroup()
                                .addComponent(EditNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                                .addComponent(EditAgetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EditPanelLayout.createSequentialGroup()
                                .addComponent(EditNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditNumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EditPanelLayout.createSequentialGroup()
                                .addComponent(EditMailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditMailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EditPanelLayout.createSequentialGroup()
                                .addComponent(EditNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(72, 72, 72))
        );
        EditPanelLayout.setVerticalGroup(
            EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditPanelLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditMailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditMailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditNumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditAgetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        getContentPane().add(EditPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 790, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumtxtActionPerformed

    private void EditProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProfileButtonActionPerformed

    private void EditBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBackButtonMouseClicked
        // TODO add your handling code here:
        UserInfoPanel.setVisible(true);
        ChangePassPanel.setVisible(false);
        EditPanel.setVisible(false);
    }//GEN-LAST:event_EditBackButtonMouseClicked

    private void EditNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditNametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditNametxtActionPerformed

    private void ChangePass_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePass_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePass_ButtonActionPerformed

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        // TODO add your handling code here:
        UserInfoPanel.setVisible(true);
        ChangePassPanel.setVisible(false);
        EditPanel.setVisible(false);
    }//GEN-LAST:event_BackButtonMouseClicked

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void MailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MailtxtActionPerformed

    private void AgetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgetxtActionPerformed

    private void ConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordActionPerformed

    private void SecuritytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecuritytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecuritytxtActionPerformed

    private void SecuritytxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SecuritytxtKeyTyped
        char e = evt.getKeyChar();
        if (Character.isDigit(e)) {
            evt.consume(); // Ignore the input if it's not a digit
        }
    }//GEN-LAST:event_SecuritytxtKeyTyped

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        // TODO add your handling code here:
       dashboard dashboard = new dashboard();
       dashboard.setVisible(true);
       dashboard.pack();
       dashboard.setLocationRelativeTo(null);  // Centers the frame on the screen
       this.dispose();
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void EditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditButtonMouseClicked
        // TODO add your handling code here:
        UserInfoPanel.setVisible(false);
        ChangePassPanel.setVisible(false);
        EditPanel.setVisible(true);
        EditMailtxt.setVisible(true);
        EditNametxt.setVisible(true);
        EditNumtxt.setVisible(true);
        EditBackButton.setVisible(true);
        EditProfileButton.setVisible(true);
        EditAgetxt.setVisible(true);
    }//GEN-LAST:event_EditButtonMouseClicked

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditButtonActionPerformed

    private void ChangePassButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePassButtonMouseClicked
        // TODO add your handling code here:
        UserInfoPanel.setVisible(false);
        ChangePassPanel.setVisible(true);
        EditPanel.setVisible(false);
        ConfirmPassword.setVisible(true);
        NewPassword.setVisible(true);
        ChangePass_Button.setVisible(true);
        BackButton.setVisible(true);
        Securitytxt.setVisible(true);
    }//GEN-LAST:event_ChangePassButtonMouseClicked

    private void ChangePassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePassButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePassButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField Agetxt;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ChangePassButton;
    private javax.swing.JPanel ChangePassPanel;
    private javax.swing.JButton ChangePass_Button;
    private javax.swing.JLabel ChangePasswordLabel;
    private javax.swing.JLabel ConfirmLabel;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JTextField EditAgetxt;
    private javax.swing.JButton EditBackButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JLabel EditMailLabel;
    private javax.swing.JTextField EditMailtxt;
    private javax.swing.JLabel EditNameLabel;
    private javax.swing.JLabel EditNameLabel2;
    private javax.swing.JTextField EditNametxt;
    private javax.swing.JLabel EditNumLabel;
    private javax.swing.JTextField EditNumtxt;
    private javax.swing.JPanel EditPanel;
    private javax.swing.JButton EditProfileButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel HeyUserLabel;
    private javax.swing.JLabel MailLabel;
    private javax.swing.JTextField Mailtxt;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField Nametxt;
    private javax.swing.JPasswordField NewPassword;
    private javax.swing.JLabel NumLabel;
    private javax.swing.JTextField Numtxt;
    private javax.swing.JLabel SecurityLabel;
    private javax.swing.JTextField Securitytxt;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JLabel UserInfoLabel;
    private javax.swing.JPanel UserInfoPanel;
    // End of variables declaration//GEN-END:variables
}
